import { BookOpen, CheckCircle2, FileText, LoaderCircle, Search, ShieldCheck, UploadCloud, X } from 'lucide-react'
import { DragEvent, FormEvent, useRef, useState } from 'react'
import { ApiError, api } from '../api'
import { EmptyState, PageHeader, Panel } from '../components'
import type { ImportResult, SearchResult } from '../types'

const maxBytes = 1024 * 1024
export default function Knowledge() {
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [dragging, setDragging] = useState(false); const [importing, setImporting] = useState(false); const [imported, setImported] = useState<ImportResult | null>(null); const [importError, setImportError] = useState<string | null>(null)
  const [query, setQuery] = useState(''); const [topK, setTopK] = useState(5); const [searching, setSearching] = useState(false); const [results, setResults] = useState<SearchResult[] | null>(null); const [searchError, setSearchError] = useState<string | null>(null)
  function choose(next: File | undefined) { setImported(null); setImportError(null); if (!next) return; const ext = next.name.toLowerCase(); if (!ext.endsWith('.txt') && !ext.endsWith('.md')) return setImportError('仅支持 .txt 或 .md 文本文件。'); if (next.size > maxBytes) return setImportError('文件超过 1 MiB 限制，请压缩内容后重试。'); setFile(next) }
  function drop(event: DragEvent) { event.preventDefault(); setDragging(false); choose(event.dataTransfer.files[0]) }
  async function upload() { if (!file) return; setImporting(true); setImportError(null); try { setImported(await api.importDocument(file)); setFile(null) } catch (err) { const apiError = err as ApiError; setImportError(apiError.kind === 'not-found' ? '知识库能力尚未在后端启用，请配置 Embedding 模型后重启服务。' : apiError.message) } finally { setImporting(false) } }
  async function search(event: FormEvent) { event.preventDefault(); setSearching(true); setSearchError(null); setResults(null); try { setResults((await api.searchKnowledge(query.trim(), topK)).results) } catch (err) { const apiError = err as ApiError; setSearchError(apiError.kind === 'not-found' ? '知识检索接口尚未启用，请检查后端 Embedding 配置。' : apiError.message) } finally { setSearching(false) } }
  return <><PageHeader eyebrow="KNOWLEDGE LAYER" title="知识库" description="导入轻量文本资料，并用真实向量检索验证 Agent 可访问的知识片段。" />
    <div className="knowledge-grid"><Panel><div className="panel-heading"><div><span className="step-label">01</span><h2>导入资料</h2></div><UploadCloud size={19} /></div>
      <button type="button" className={`dropzone ${dragging ? 'is-dragging' : ''}`} onClick={() => inputRef.current?.click()} onDragOver={e => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={drop}><span className="upload-icon"><UploadCloud size={25} /></span><strong>拖拽文件到这里</strong><p>或点击从本地选择文件</p><small>.TXT / .MD · 最大 1 MiB · UTF-8</small></button><input ref={inputRef} hidden type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e => choose(e.target.files?.[0])} />
      {file && <div className="selected-file"><FileText size={19} /><div><strong>{file.name}</strong><small>{(file.size / 1024).toFixed(1)} KiB</small></div><button onClick={() => setFile(null)}><X size={16} /></button></div>}
      {importError && <div className="inline-error">{importError}</div>}{imported && <div className="import-success"><CheckCircle2 size={20} /><div><strong>知识导入完成</strong><span>{imported.source} · {imported.chunk_count} 个 Chunk</span></div></div>}
      <button className="button button-primary button-wide" onClick={upload} disabled={!file || importing}>{importing ? <><LoaderCircle size={17} className="spin" />正在向量化…</> : <><UploadCloud size={17} />导入知识库</>}</button>
      <div className="process-note"><ShieldCheck size={16} /><span>文件由后端切分、Embedding 并写入 Qdrant，浏览器不接触模型密钥。</span></div>
    </Panel>
    <Panel><div className="panel-heading"><div><span className="step-label">02</span><h2>检索测试</h2></div><Search size={19} /></div><form onSubmit={search} className="search-form"><label>检索问题<textarea value={query} onChange={e => setQuery(e.target.value)} rows={4} placeholder="例如：退款申请需要满足哪些条件？" required /></label><label>TopK <span>{topK} 个结果</span><input type="range" min="1" max="10" value={topK} onChange={e => setTopK(Number(e.target.value))} /></label><button className="button button-primary button-wide" disabled={!query.trim() || searching}>{searching ? <><LoaderCircle size={17} className="spin" />正在检索…</> : <><Search size={17} />测试知识检索</>}</button></form>{searchError && <div className="inline-error">{searchError}</div>}</Panel></div>
    <Panel className="results-panel"><div className="panel-heading"><div><span className="eyebrow">SEMANTIC RESULTS</span><h2>检索结果</h2></div>{results && <span className="muted">返回 {results.length} 个片段</span>}</div>{results === null ? <EmptyState title="等待一次检索" description="导入资料后，输入问题查看来源、相似度分数和原始文本片段。" /> : results.length === 0 ? <EmptyState title="没有匹配片段" description="尝试换一种问法，或先导入相关知识资料。" /> : <div className="search-results">{results.map((result, index) => <article key={`${result.document_id}-${result.chunk_index}`}><div className="result-rank">{String(index + 1).padStart(2, '0')}</div><div><div className="result-head"><strong><BookOpen size={14} />{result.source}</strong><span>Chunk {result.chunk_index}</span><em>{(result.score * 100).toFixed(1)}%</em></div><p>{result.text}</p></div></article>)}</div>}</Panel>
  </>
}
